runtime: python39
entrypoint: gunicorn -b :$PORT src.app:app

env_variables:
  FLASK_APP: "src/app.py"
  SECRET_KEY: "sua_chave_secreta"

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10 